steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args:
  - 'build'
  - '.'
  - '-t'
  - 'gcr.io/$PROJECT_ID/team-api-test:latest'

#Push image to container registry
- name: 'gcr.io/cloud=builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/constellationsweb:latest'
