#This step builds the container image.
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args:
  - 'build'
  - '.'
  - '-t'
  - 'gcr.io/$PROJECT_ID/team-api-test:latest'

#Above command runs: docker-build -t gcr.io/PROJECT_ID/constellationweb:latest .

#This step pushes the image to the container registry.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/constellationweb:latest'